app:
  name: ${DEPLOYABLE_NAME}
  env: ${ENVIRONMENT}
  log_level: ${APP_LOG_LEVEL}
  port: ${APP_PORT}
  metric_sampling_rate: ${APP_METRIC_SAMPLING_RATE}

auth:
  jwt_secret: ${JWT_SECRET}
  google_client_id: ${GOOGLE_CLIENT_ID}